FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

COPY . ./

RUN dotnet restore 

RUN dotnet publish -c release -o /Publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0

EXPOSE 5050

ENV ASPNETCORE_URLS="http://0.0.0.0:5050"

WORKDIR /Aplicacion

COPY --from=build /Publish ./

ENTRYPOINT ["dotnet", "api.dll"]